### PR TITLE
Retry Logic for Dynamo Client

### LINKED ISSUE #15: Retry logic for Dynamo table calls
It's likely that these fail, so make a wrapper caller that tries to call to dynamo 3 times before failing out and replace all calls with that.

### PR DESCRIPTION
**Pull request by akpiya**
Resolves #15

Dynamo client will retry 3 times which should be good enough for our purposes.

### CODE REVIEW

File: internal/storage/dynamo.go [hunk 1]
```diff
@@ -43,5 +43,7 @@ func initializeDynamo() {
 
 	dynamoClient = dynamodb.NewFromConfig(awsCfg, func(o *dynamodb.Options) {
 		o.BaseEndpoint = aws.String(cfg.DynamoDBEndpoint)
+		o.RetryMode = aws.RetryModeStandard
```
Comment (kathirmeyyappan) [inline internal/storage/dynamo.go:46]: oh this is pretty neat lol, didn't know you could do it in dynamo config

**Review by kathirmeyyappan — APPROVED** [review]
lgtm
